### PR TITLE
Create Code_Of_Conduct.md

### LINKED ISSUE #42: Add Code of Conduct
We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow these instructions on how to add a Code of Conduct.

Sample: https://github.com/Girlscript-WOB/Guidelines/blob/main/Project%20Admins/Code%20of%20conduct.md

### PR DESCRIPTION
**Pull request by KiranBaliga**
closes #42 

This PR addresses the addition of a code of conduct markdown file for the Project Brave Repository.

Please review the PR and action accordingly.

Thank you!

### CODE REVIEW

**Comment by KiranBaliga** [comment]
@subhadeeproy3902 Please authorize and review the PR. Thank you!

**Comment by KiranBaliga** [comment]
@subhadeeproy3902 Please authorize and review the PR. Thank you!

**Comment by KiranBaliga** [comment]
@subhadeeproy3902 please review

**Comment by Xeven777** [comment]
Merged 👨🏻‍💻

**Pull request merged**
